import { locale } from './i18n.ts';

const messages: Record<string, string> = {
  '控制器未响应，请检查地址、网络和 TLS 证书。': 'The controller did not respond. Check its address, network and TLS certificate.',
  '控制器响应中断。': 'The controller response was interrupted.',
  '本机控制器地址无效。': 'The local controller address is invalid.',
  '内核返回的 WebUI 配置无效。': 'The core returned an invalid WebUI configuration.',
  'WebUI 控制器地址无效。': 'The WebUI controller address is invalid.',
  'WebUI 控制器缺少主机名。': 'The WebUI controller hostname is missing.',
  'WebUI 控制器缺少端口。': 'The WebUI controller port is missing.',
  '日志级别无效。': 'The log level is invalid.',
  '日志流连接超时。': 'The log stream connection timed out.',
  '无法连接日志流。': 'Unable to connect to the log stream.',
  '日志流连接中断。': 'The log stream connection was interrupted.',
  '日志流单条消息超过 64 KiB。': 'A log stream message exceeds 64 KiB.',
  '日志流已结束，正在重新连接。': 'The log stream ended. Reconnecting.',
  '监控流类型无效。': 'The monitoring stream type is invalid.',
  '监控流地址无效。': 'The monitoring stream address is invalid.',
  '监控流鉴权设置无效。': 'The monitoring stream authentication is invalid.',
  '监控流连接超时。': 'The monitoring stream connection timed out.',
  '无法连接监控流，请检查地址、网络和 TLS 证书。': 'Unable to connect to monitoring. Check the address, network and TLS certificate.',
  '监控流长时间未响应，正在重新连接。': 'The monitoring stream is unresponsive. Reconnecting.',
  '监控流连接中断。': 'The monitoring stream connection was interrupted.',
  '监控流已结束，正在重新连接。': 'The monitoring stream ended. Reconnecting.',
  '监控流连接中断或消息超过大小限制。': 'The monitoring connection was interrupted or a message exceeded the size limit.',
  '监控流消息超过大小限制。': 'A monitoring message exceeds the size limit.',
  '无法连接监控流。': 'Unable to connect to the monitoring stream.',
  'TUN 运行状态与请求不一致，请检查内核权限与日志。': 'The TUN state does not match the request. Check core permissions and logs.',
  'TUN 内核运行状态与保存设置不一致，请检查权限与日志。': 'The TUN state does not match saved settings. Check permissions and logs.',
  '内核未应用所选 TUN 协议栈，请检查内核版本与日志。': 'The core did not apply the TUN stack. Check its version and logs.',
  'TUN 协议栈必须为 system、gvisor、mixed 或 mips。': 'Choose system, gvisor, mixed or mips as the TUN stack.',
  '当前内核未返回 TUN 配置。': 'The core did not return a TUN configuration.',
  '当前内核未返回有效的 TUN 启用状态。': 'The core did not return a valid TUN state.',
  '代理端口格式无效。': 'The proxy port format is invalid.',
  '内核返回的代理提供者数据无效。': 'The core returned invalid proxy provider data.',
  '代理组不存在。': 'The proxy group does not exist.',
  '所选项目不是代理组。': 'The selected item is not a proxy group.',
  '内核返回的规则提供者数据无效。': 'The core returned invalid rule provider data.',
  '内核升级请求未完成，请检查控制器连接后重试。': 'The core update request failed. Check the controller connection and retry.',
  '内核升级响应超过 64 KiB。': 'The core update response exceeds 64 KiB.',
  '内核升级响应中断。': 'The core update response was interrupted.',
  '请先切换到本机，再执行本地内核或配置操作。': 'Switch to the local machine before managing its core or profiles.',
  '远程机器不存在。': 'The remote machine does not exist.',
  '无法连接远程机器。': 'Unable to connect to the remote machine.',
  '最多保存 64 台远程机器。': 'You can save up to 64 remote machines.',
  '请先选择远程机器。': 'Select a remote machine first.',
  '请先关闭本机系统代理，再关闭远程内核的全部代理端口。': 'Disable the local system proxy before closing all remote proxy ports.',
  '请先选择 mihomo 内核。': 'Select a mihomo executable first.',
  '远程端口保存失败，已恢复原内核端口：': 'Saving remote ports failed; the previous ports were restored: ',
  '远程端口保存失败：': 'Saving remote ports failed: ', '原端口恢复失败：': ' Restoring previous ports failed: ',
  '无法创建配置回收目录：': 'Unable to create the profile recovery folder: ',
  '无法移除配置文件：': 'Unable to remove the profile file: ',
  '配置文件恢复失败：': ' Restoring the profile file failed: ', '原配置恢复失败：': ' Restoring the previous profile failed: ',
  '恢复内核运行设置失败：': ' Restoring core settings failed: ',
  '保存设置失败，已恢复原值：': 'Saving settings failed; previous values were restored: ', '保存设置失败：': 'Saving settings failed: ',
  '无法读取系统登录启动项。': 'Unable to read the system login startup entry.',
  '无法更改开机自启：': 'Unable to change launch at login: ',
  '无法确认系统登录启动项状态。': 'Unable to confirm the system login startup state.',
  '系统登录启动项未生效，请检查系统设置后重试。': 'The login startup entry did not take effect. Check system settings and retry.',
  '无法写入系统剪贴板。': 'Unable to write to the system clipboard.',
  '无法打开系统默认浏览器。': 'Unable to open the default browser.',
  '目标目录不存在。': 'The target folder does not exist.', '无法打开目录：': 'Unable to open the folder: ',
  '此平台尚未接入系统代理管理。': 'System proxy management is unavailable on this platform.',
  '代理绕过列表最多保存 256 项。': 'The proxy bypass list supports up to 256 entries.',
  '代理绕过项不能包含控制字符或分号，每项最多 512 字节。': 'Bypass entries cannot contain control characters or semicolons, and must be at most 512 bytes.',
  '代理绕过的 IPv4 CIDR 前缀无效。': 'The bypass IPv4 CIDR prefix is invalid.',
  '代理绕过的 IPv4 CIDR 前缀必须为 0 至 32。': 'The bypass IPv4 CIDR prefix must be from 0 to 32.',
  '远程内核没有启用 HTTP、SOCKS 或混合代理端口。': 'The remote core has no enabled HTTP, SOCKS or mixed port.',
  '已启用的代理端口不能重复；填 0 可关闭对应监听。': 'Enabled proxy ports must be unique. Set a port to 0 to disable it.',
  '此平台尚未接入 Wi-Fi 网络名称查询。': 'Wi-Fi name lookup is unavailable on this platform.',
  '无法读取当前 Wi-Fi 名称。请在 Windows 定位设置中允许访问后重试。': 'Unable to read the Wi-Fi name. Allow access in Windows location settings and retry.',
  'Windows WLAN 服务未运行或暂时不可用。': 'The Windows WLAN service is stopped or temporarily unavailable.',
  'Windows 返回的 Wi-Fi 数据无效。': 'Windows returned invalid Wi-Fi data.',
  '当前 Wi-Fi 名称不是有效的 UTF-8 文本，无法绑定到配置。': 'The Wi-Fi name is not valid UTF-8 and cannot be bound to a profile.',
  '远程机器标识无效。': 'The remote machine identifier is invalid.',
  '名称需为 1–180 个字符，且不能包含控制字符。': 'Use a name of 1–180 characters without control characters.',
  '密钥需为不超过 4096 字节的可打印 ASCII 字符。': 'Use a secret of at most 4096 bytes containing printable ASCII characters.',
  '端口需为 1–65535 之间的整数。': 'Use a whole-number port from 1 to 65535.',
  '主机地址无效。': 'The host address is invalid.',
  '请输入主机名或 IP 地址，不要包含协议、端口或路径。': 'Enter a hostname or IP without a scheme, port or path.',
  'IPv6 地址无效；端口请填写在单独的端口字段。': 'The IPv6 address is invalid. Use the separate port field.',
  '连接超时。': 'The connection timed out.',
  '订阅关联的配置标识无效。': 'The subscription profile identifier is invalid.',
  '订阅自动更新间隔至少为 1 小时。': 'The subscription interval must be at least 1 hour.',
  '最多保存 128 个订阅。': 'You can save up to 128 subscriptions.',
  '一个配置只能关联一个订阅来源。': 'A profile can have only one subscription source.',
  '订阅关联的配置不存在。': 'The subscription profile does not exist.',
  '订阅地址过长。': 'The subscription URL is too long.',
  '请输入有效的 HTTP 或 HTTPS 订阅地址。': 'Enter a valid HTTP or HTTPS subscription URL.',
  '订阅地址不能包含用户名、密码或片段。': 'The subscription URL cannot contain a username, password or fragment.',
  '订阅地址需要有效的主机名和端口。': 'The subscription URL needs a valid hostname and port.',
  '订阅 DNS 查询超时。': 'The subscription DNS lookup timed out.',
  '无法解析订阅主机名。': 'Unable to resolve the subscription hostname.',
  '无法创建订阅下载连接。': 'Unable to create a subscription download connection.',
  '无法下载订阅，请检查地址和网络连接。': 'Unable to download the subscription. Check its URL and network connection.',
  '订阅下载已中断。': 'The subscription download was interrupted.',
  '订阅超过 8 MiB 大小限制。': 'The subscription exceeds the 8 MiB size limit.',
  '订阅重定向次数过多。': 'The subscription has too many redirects.',
  '订阅服务器返回无效重定向地址。': 'The subscription server returned an invalid redirect.',
  '订阅重定向不能访问本地、私有或保留地址。': 'Subscription redirects cannot access local, private or reserved addresses.',
  '订阅重定向不能从 HTTPS 降级为 HTTP。': 'Subscription redirects cannot downgrade HTTPS to HTTP.',
  '订阅下载超时。': 'The subscription download timed out.',
  '订阅内容不是有效的 mihomo YAML 配置。': 'The subscription is not valid mihomo YAML.',
  '无法保存订阅配置。': 'Unable to save the subscription profile.',
  '订阅更新失败，请检查地址、网络连接和配置内容。': 'Subscription update failed. Check its URL, network and configuration.',
  '配置名称需为 1–180 个字符，且不能包含控制字符。': 'Use a profile name of 1–180 characters without control characters.',
  '配置名称需使用 .yaml 或 .yml 扩展名。': 'Use the .yaml or .yml extension for the profile name.',
  '配置名称含扩展名最多为 180 个字符。': 'The profile name including its extension must be at most 180 characters.',
  '该配置没有订阅来源。': 'This profile has no subscription source.',
  '订阅更新间隔需为 1–8760 小时。': 'Use a subscription interval from 1 to 8760 hours.',
  '订阅元数据保存失败，已恢复原配置：': 'Saving subscription metadata failed; the previous profile was restored: ',
  '订阅元数据保存失败：': 'Saving subscription metadata failed: ',
  '恢复配置失败：': ' Restoring the profile failed: ',
  '发布页地址无效。': 'The release page URL is invalid.',
  '只允许打开 ClashBar 官方 GitHub 发布页。': 'Only the official ClashBar GitHub release page can be opened.',
  '无法创建版本检查连接。': 'Unable to create the update check connection.',
  '无法检查 ClashBar 更新，请检查网络连接。': 'Unable to check ClashBar updates. Check the network connection.',
  '版本检查响应超过 1 MiB。': 'The update check response exceeds 1 MiB.',
  '版本检查响应中断。': 'The update check response was interrupted.',
  '版本检查返回了无效的发布信息。': 'The update check returned invalid release information.',
  '发布版本号无效。': 'The release version is invalid.',
  'TUN 授权失败': 'TUN authorization failed', '保存绕过失败': 'Saving bypass settings failed',
  '内核没有返回当前设置值。': 'The core did not return the current setting.',
  '恢复内核设置失败：': ' Restoring core settings failed: ',
  '请先关闭系统代理，再关闭全部 HTTP、SOCKS 和混合代理端口。': 'Disable the system proxy before closing all HTTP, SOCKS and mixed ports.',
  '设置应用失败，已恢复原设置与内核：': 'Applying settings failed; the previous settings and core were restored: ',
  '设置应用失败：': 'Applying settings failed: ', '停止候选内核失败：': ' Stopping the candidate core failed: ', '恢复原内核失败：': ' Restoring the previous core failed: ',
  '绕过设置应用失败：': 'Applying bypass settings failed: ', '恢复保存值失败：': ' Restoring saved values failed: ',
  '恢复 TUN 状态失败：': ' Restoring TUN state failed: ',
  '保存 TUN 设置失败，已恢复运行状态：': 'Saving TUN settings failed; the previous runtime state was restored: ',
  '保存 TUN 设置失败：': 'Saving TUN settings failed: ', '恢复运行状态失败：': ' Restoring runtime state failed: ',
  '读取 Wi-Fi 状态任务失败。': 'The Wi-Fi state query failed.',
  'Wi-Fi 绑定的配置不存在。': 'The profile bound to Wi-Fi no longer exists.',
  '请先启用 SSID 自动切换。': 'Enable SSID auto switching first.',
  '配置不存在。': 'The profile does not exist.',
  '当前 Wi-Fi 名称不可用，请检查定位权限与网络连接。': 'The Wi-Fi name is unavailable. Check location permission and the network connection.',
  '无法检查内核权限：': 'Unable to check core privileges: ', '无法读取内核权限：': 'Unable to read core privileges: ',
  '无法核对内核权限请求文件。': 'Unable to verify the core authorization request file.',
  '无法读取内核权限请求文件。': 'Unable to read the core authorization request file.',
  '提权助手路径不是有效 Unicode。': 'The elevation helper path is not valid Unicode.',
  '提权助手路径包含无效字符。': 'The elevation helper path contains invalid characters.',
  '无法准备内核权限请求：': 'Unable to prepare core authorization: ',
  '已取消 TUN 管理员授权。': 'TUN administrator authorization was cancelled.',
  '无法授权 TUN 内核：': 'Unable to authorize the TUN core: ',
  'Windows 未返回提权内核助手的进程句柄。': 'Windows did not return the elevated core helper process handle.',
  '无法等待提权内核助手：': 'Unable to wait for the elevated core helper: ',
  '无法检查提权内核状态：': 'Unable to check the elevated core state: ',
  '提权内核助手未在 8 秒内停止；保留恢复文件以便重试。': 'The elevated core helper did not stop within 8 seconds. Recovery files were retained for retry.',
  '无法读取内核权限请求。': 'Unable to read the core authorization request.',
  '内核权限请求过大。': 'The core authorization request is too large.',
  '内核权限请求已发生变化，取消提权。': 'The core authorization request changed. Elevation was cancelled.',
  '内核权限请求格式无效。': 'The core authorization request format is invalid.',
  '内核权限请求目录无效。': 'The core authorization request folder is invalid.',
  '内核权限请求必须使用当前运行目录中的配置。': 'The authorization request must use a profile in the current runtime folder.',
  '无法清理内核权限请求：': 'Unable to clean up the core authorization request: ',
  'TUN 内核助手没有管理员权限。': 'The TUN core helper does not have administrator privileges.',
  '无法锁定已授权的内核文件。': 'Unable to lock the authorized core executable.',
  '无法锁定已授权的内核配置。': 'Unable to lock the authorized core configuration.',
  '内核或配置在授权期间发生变化，取消提权。': 'The core or configuration changed during authorization. Elevation was cancelled.',
  '主程序已经退出，取消启动 TUN 内核。': 'The app has exited. TUN core startup was cancelled.',
  'TUN 内核已退出：': 'The TUN core exited: ',
};
const replacements = Object.entries(messages).sort(([left], [right]) => right.length - left.length);

// 只翻译应用拥有的错误文案；系统原始错误、配置名与内核日志保留原文。
export function localizeBackendError(message: string, language = locale): string {
  if (language !== 'en') return message;
  let result = message
    .replace(/代理 (TCP|UDP) 端口 (\d+) 已被占用，请在设置中更换。/g, 'Proxy $1 port $2 is in use. Change it in settings.')
    .replace(/控制端口 (\d+) 已被占用。/g, 'Controller port $1 is in use.')
    .replace(/(控制器|日志流|监控流|订阅服务器|版本检查)返回 HTTP (\d+)。/g, (_, owner: string, code: string) => `${({ 控制器: 'Controller', 日志流: 'Log stream', 监控流: 'Monitoring stream', 订阅服务器: 'Subscription server', 版本检查: 'Update check' } as Record<string, string>)[owner]} returned HTTP ${code}.`)
    .replace(/读取 Wi-Fi 状态失败，Windows 错误码：(\d+)。/g, 'Unable to read Wi-Fi state. Windows error: $1.')
    .replace(/当前 Wi-Fi 绑定的配置“(.+?)”已不存在。/g, 'The profile “$1” bound to the current Wi-Fi no longer exists.')
    .replace(/配置“(.+?)”已存在，请确认覆盖。/g, 'Profile “$1” already exists. Confirm to overwrite it.')
    .replace(/mips 协议栈需要 mihomo ([\d.]+) 或更新版本。/g, 'The mips stack requires mihomo $1 or later.')
    .replace(/当前内核未返回 (.+?) 设置。/g, 'The core did not return the $1 setting.')
    .replace(/内核未返回有效的 (.+?) 端口。/g, 'The core did not return a valid $1 port.')
    .replace(/内核升级返回了无效响应（HTTP (\d+)）。/g, 'The core update returned an invalid response (HTTP $1).')
    .replace(/内核升级失败（HTTP (\d+)）：/g, 'Core update failed (HTTP $1): ')
    .replace(/订阅更新完成：成功 (\d+) 项，失败 (\d+) 项。请在订阅设置中查看失败原因。/g, 'Subscription updates: $1 succeeded, $2 failed. Open subscription settings for details.')
    .replace(/规则提供者更新完成 (\d+)\/(\d+)；失败：(.+?)。可再次刷新重试。/g, 'Rule providers updated: $1/$2. Failed: $3. Refresh to retry.');
  for (const [source, translated] of replacements) result = result.split(source).join(translated);
  return result;
}
