export const locale: 'zh-CN' | 'en' = typeof localStorage !== 'undefined' && localStorage.getItem('clashbar-language') === 'en' ? 'en' : 'zh-CN';
if (typeof document !== 'undefined') document.documentElement.lang = locale;

const english: Record<string, string> = {
  '节点': 'Proxies', '分流': 'Rules', '连接': 'Connections', '日志': 'Logs', '设置': 'Settings', '全部': 'All',
  '默认顺序': 'Default', '无法打开菜单。{0}': 'Unable to open the menu. {0}', '打开 WebUI': 'Open WebUI',
  '固定面板': 'Pin panel', '取消固定': 'Unpin panel', '重启内核': 'Restart core', '启动内核': 'Start core', '停止内核': 'Stop core', '退出 ClashBar': 'Quit ClashBar',
  '代理模式': 'Proxy mode', '规则': 'Rule', '全局': 'Global', '直连': 'Direct', '切换代理模式': 'Change proxy mode', '{0}模式': '{0} mode', '功能页面': 'Pages', '重新读取': 'Reload',
  '此页面需要 ClashBar 桌面应用。浏览器无法管理本机内核和系统代理。': 'Open this page in the ClashBar desktop app to manage the local core and system proxy.',
  '更新或选择 mihomo 内核': 'Update or select mihomo core', '检查 ClashBar 更新': 'Check ClashBar updates', '代理流量': 'Proxy traffic', '未导入': 'Not imported', '切换配置': 'Profile',
  '系统代理': 'System proxy', '系统代理当前指向远程内核，请确认远程地址可达。': 'The system proxy uses a remote core. Check that its address is reachable.', '开启系统代理': 'Enable system proxy', '关闭系统代理': 'Disable system proxy',
  '更改 TUN 协议栈': 'Change TUN stack', 'TUN 模式': 'TUN mode', '开启 TUN': 'Enable TUN', '关闭 TUN': 'Disable TUN',
  '已复制 PowerShell 代理命令': 'PowerShell proxy command copied', '已复制': 'Copied', '复制 PowerShell 代理命令': 'Copy PowerShell proxy command', '远程': 'Remote', '已复制当前端点命令': 'Endpoint command copied', '复制当前端点命令': 'Copy endpoint command', '复制终端命令': 'Terminal command',
  '代理提供者': 'Proxy providers', '折叠代理提供者': 'Collapse providers', '代理组': 'Proxy groups', '按延迟排序节点': 'Sort proxies by latency', '显示延迟历史': 'Show latency history', '显示隐藏代理组': 'Show hidden proxy groups', '测试全部代理组延迟': 'Test all group latencies',
  '按策略分组': 'Group by policy', '刷新规则': 'Refresh rules', '刷新规则提供者': 'Refresh rule providers', '搜索目标、类型、策略...': 'Search target, type, policy...', '筛选策略': 'Filter policy', '全部策略': 'All policies',
  '连接协议': 'Transport', '全部协议': 'All protocols', '仅 TCP': 'TCP only', '仅 UDP': 'UDP only', '其他协议': 'Other protocols', '连接排序': 'Sort connections', '最新连接': 'Newest', '最早连接': 'Oldest', '上传流量高到低': 'Upload descending', '下载流量高到低': 'Download descending', '总流量高到低': 'Total descending', '关闭全部连接': 'Close all connections', '过滤域名、IP...': 'Filter domain, IP...',
  '内核日志级别': 'Core log level', '更改日志级别': 'Change log level', '复制全部日志': 'Copy all logs', '已复制全部日志': 'All logs copied', '清理全部日志': 'Clear all logs', '搜索日志...': 'Search logs...', '内核日志': 'Core logs',
  '基础设置': 'General settings', '开机自启': 'Launch at login', '内核自启': 'Start core on launch', '更改{0}': 'Change {0}', '图标和网速': 'Icon and speed', '状态栏样式': 'Tray style', '仅图标': 'Icon only', '仅网速': 'Speed only', '更改状态栏样式': 'Change tray style',
  '跟随系统': 'System', '外观模式': 'Appearance', '浅色': 'Light', '深色': 'Dark', '设置内核日志级别': 'Set core log level', '日志级别': 'Log level', '编辑': 'Edit', '代理绕过': 'Proxy bypass', '设置地址': 'Set address', '内核设置': 'Core settings', '允许局域网': 'Allow LAN', 'TCP 并发': 'TCP concurrent',
  '允许同一局域网内的设备连接代理端口；控制器仍只接受本机连接。': 'Allow devices on your LAN to use proxy ports. The controller remains local.', '管理内核': 'Manage core', 'mihomo 内核': 'mihomo core', '代理端口': 'Proxy ports', 'HTTP 端口': 'HTTP port', 'SOCKS 端口': 'SOCKS port', '混合端口': 'Mixed port', '控制端口': 'Controller port', '重定向端口': 'Redir port', 'TProxy 端口': 'TProxy port',
  '代理端口和控制端口不能相同。': 'Proxy ports and the controller port must differ.', '保存端口': 'Save ports', '已保存': 'Saved', '系统维护': 'Maintenance', '清理 FakeIP 缓存': 'Flush FakeIP cache', '清理 DNS 缓存': 'Flush DNS cache', '更新 Geo 数据库': 'Update Geo database', '打开内核目录': 'Open core folder',
  '更换内核或本机端口前请先停止内核。': 'Stop the core before changing the executable or local ports.', '选择本机内核...': 'Select local core...', '选择内核': 'Select core', '更新 mihomo 内核': 'Update mihomo core', '发现新版本 {0}': 'Update available: {0}', '已是最新版本': 'You are up to date', '当前版本 {0} · 最新版本 {1}': 'Current {0} · Latest {1}', '关闭': 'Close', '打开发布页': 'Open release page', 'WebUI 地址': 'WebUI address', '取消': 'Cancel', '保存': 'Save',
  '地址不包含控制器密钥；在 WebUI 内连接对应控制器。': 'Do not include the controller secret in this address. Connect from within the WebUI.', '请输入不含密钥、查询参数或片段的 HTTP(S) 地址。': 'Enter an HTTP(S) address without credentials, query parameters or fragments.', '每行一个域名、IP 或通配符': 'One domain, IP or wildcard per line', '保存绕过': 'Save bypass', '恢复默认': 'Defaults', '保存代理绕过': 'Save proxy bypass',
  'Wi-Fi 自动切换': 'Wi-Fi auto switching', '当前 Wi-Fi：{0}': 'Current Wi-Fi: {0}', '未读取到 Wi-Fi 名称。启用或刷新后读取当前网络。': 'No Wi-Fi name is available. Enable or refresh to read the current network.', '停用自动切换': 'Disable auto switching', '启用自动切换': 'Enable auto switching', '更改 SSID 自动切换': 'Change SSID auto switching', '刷新 Wi-Fi': 'Refresh Wi-Fi',
  '在配置菜单中选择“绑定当前 Wi-Fi”，连接该网络时将自动切换配置。': 'Use “Bind current Wi-Fi” in a profile menu to switch to that profile when connecting to the network.', '解绑 Wi-Fi {0}': 'Unbind Wi-Fi {0}', '解绑 Wi-Fi': 'Unbind Wi-Fi', '本机': 'Local', '管理远程机器': 'Remote machines', '请先修正并保存端口设置，再管理远程机器。': 'Correct and save the port settings before managing remote machines.', '控制器': 'Controller', '请先修正并保存端口设置，再切换机器。': 'Correct and save the port settings before switching machines.', '切换机器': 'Switch machine',
  '订阅': 'Subscription', '本地': 'Local', '更新失败': 'Update failed', '管理配置 {0}': 'Manage profile {0}', '导入配置文件...': 'Import profile file...', '导入配置': 'Import profile', '导入订阅链接...': 'Import subscription...', '更新全部订阅': 'Update all subscriptions', '重新加载配置列表': 'Reload profiles', '打开配置目录': 'Open profiles folder', 'SSID 自动切换': 'SSID auto switching', '管理 Wi-Fi 绑定...': 'Manage Wi-Fi bindings...', '配置文件': 'Profiles',
  '更新订阅': 'Update subscription', '编辑订阅与自动更新...': 'Edit subscription and schedule...', '复制订阅链接': 'Copy subscription URL', '解绑当前 Wi-Fi {0}': 'Unbind current Wi-Fi {0}', '绑定当前 Wi-Fi {0}': 'Bind current Wi-Fi {0}', '更改 Wi-Fi 绑定': 'Change Wi-Fi binding', '删除配置': 'Delete profile', '返回配置列表': 'Back to profiles', '删除配置「{0}」？': 'Delete profile “{0}”?',
  '这是最后一个配置，删除后将停止内核。': 'This is the last profile. Deleting it will stop the core. ', '删除后将切换到列表中的首个可用配置。': 'The first remaining profile will become active. ', '当前使用的配置不受影响。': 'The active profile will not change. ', '{0}文件移至应用的配置回收目录，原始导入文件不受影响。': '{0}The file moves to the app recovery folder. The original imported file is unchanged.',
  '编辑订阅': 'Edit subscription', '导入订阅链接': 'Import subscription', '订阅链接': 'Subscription URL', '留空保留已有链接': 'Leave blank to retain the URL', '配置名称（可选）': 'Profile name (optional)', '更新间隔（小时）': 'Update interval (hours)', '自动更新': 'Auto update', '显示链接': 'Show URL', '隐藏链接': 'Hide URL', '保存订阅': 'Save subscription', '导入订阅': 'Import subscription', '订阅来源：{0}。留空保留已有链接。': 'Source: {0}. Leave the URL blank to keep it.', '使用 HTTPS 链接导入；已有配置会保留，可随时切换。': 'Import an HTTPS subscription. Existing profiles remain available.', '更新间隔需为 1–8760 小时的整数。': 'Use a whole number from 1 to 8760 hours.',
  '{0}控制器，{1}': '{0} controller, {1}', '运行中': 'Running', '已停止': 'Stopped', '(远程连接不可变更)': '(Managed remotely)', '本机系统代理当前指向 {0}': 'Local system proxy points to {0}', '控制本机系统代理，启用后使用当前选中内核的代理端口。': 'Use the selected core as this computer’s system proxy.', '尚未选择 mihomo.exe': 'No mihomo executable selected', '远程机器的内核由该机器管理。': 'The remote machine manages its own core.', '更换内核或本机端口前请先停止内核。TUN 按需请求系统授权。': 'Stop the core before changing its executable or local ports. TUN requests system permission when needed.', '端口修改作用于远程内核，0 表示关闭。本机启动设置不受影响。': 'Ports apply to the remote core; 0 disables a port. Local startup settings are unchanged.', '应用设置 (本地)': 'App settings (local)', '内核设置 (远程)': 'Core settings (remote)', '当前内核未返回此端口。': 'The core did not report this port.',
  '只修改远程代理的局域网访问设置，不修改远程控制器监听地址。': 'Changes remote proxy LAN access only, preserving the controller address.', '启动内核后更改此设置。': 'Start the core to change this setting.', '当前内核未返回此设置。': 'The core did not report this setting.', '正在读取数据': 'Loading data', '内核未启动': 'Core is stopped', '读取失败时可重新刷新。': 'Refresh to retry if loading fails.', '点击顶部启动按钮。': 'Use the Start button above.', '选择 mihomo 内核并导入配置后启动。': 'Select a mihomo executable and import a profile to start.', '超时': 'Timeout', '测试延迟': 'Test latency', '切换节点': 'Select proxy', '测试 {0} 延迟': 'Test {0} latency', '代理组 {0}': 'Proxy group {0}', '测试 {0} 分组延迟': 'Test group {0} latency', '测试分组延迟': 'Test group latency',
  '暂无代理组': 'No proxy groups', '当前配置没有可用的代理组。': 'This profile contains no available proxy groups.', '展开代理提供者': 'Expand providers', '更新代理提供者 {0}': 'Update provider {0}', '更新代理提供者': 'Update provider', '不限时': 'No expiry', '已过期': 'Expired', '剩 {0} 天': '{0} days left', '{0} 订阅用量': '{0} subscription usage', '暂无代理提供者': 'No proxy providers', '刚刚': 'Just now', '{0}m前': '{0}m ago', '{0}h前': '{0}h ago', '域名': 'Domain', '规则集': 'Rule set', '其他': 'Other', '规则 {0}  规则集 {1}': 'Rules {0}  Sets {1}', '无匹配规则': 'No matching rules', '暂无规则数据': 'No rules', '修改或清除筛选条件。': 'Change or clear the filters.', '当前配置没有路由规则。': 'This profile has no routing rules.', '目标 / 类型': 'Target / Type', '策略': 'Policy', '统计': 'Stats', '路由规则': 'Routing rules',
  '关闭连接 {0}': 'Close connection {0}', '关闭连接': 'Close connection', '复制 Host': 'Copy host', '已复制 Host': 'Host copied', '复制连接 ID': 'Copy connection ID', '已复制连接 ID': 'Connection ID copied', '无匹配连接': 'No matching connections', '暂无活动连接': 'No active connections', '通过代理访问网络后，连接会显示在这里。': 'Connections appear when traffic passes through the proxy.', '错误': 'Error', '警告': 'Warning', '信息': 'Info', '复制日志': 'Copy log', '已复制日志': 'Log copied', '无匹配日志': 'No matching logs', '暂无日志': 'No logs', '启动内核后查看日志。': 'Start the core to view logs.', '复制失败，请检查剪贴板权限后重试。': 'Copy failed. Check clipboard permission and retry.', '读取失败，显示上次数据。{0}': 'Read failed; showing previous data. {0}', '{0}未完成。{1}': '{0} failed. {1}', '已完成': ' completed', '未完成': ' failed', '{0}已完成。': '{0} completed.', '托盘连接失败。{0}': 'Tray connection failed. {0}',
  '返回编辑': 'Back to editing', '返回机器列表': 'Back to machines', '已连接 · {0}': 'Connected · {0}', '连接失败 · {0}': 'Connection failed · {0}', '请检查地址与密钥': 'Check address and secret', '检查中…': 'Checking…', '编辑机器 {0}': 'Edit machine {0}', '删除机器 {0}': 'Delete machine {0}', '添加机器': 'Add machine', '编辑机器': 'Edit machine', '放弃未保存的更改？': 'Discard unsaved changes?', '机器信息尚未保存。可以继续编辑，或放弃这次修改。': 'Machine details are unsaved. Continue editing or discard these changes.', '继续编辑': 'Keep editing', '放弃修改': 'Discard changes', '名称': 'Name', '主机地址': 'Host', '端口': 'Port', '密钥': 'Secret', '留空保留已保存的密钥': 'Leave blank to keep saved secret', '可选': 'Optional', '显示密钥': 'Show secret', '隐藏密钥': 'Hide secret', '清除已保存的密钥': 'Clear saved secret', '预览：{0}://{1}:{2}': 'Preview: {0}://{1}:{2}', '请输入机器名称。': 'Enter a machine name.', '请输入主机名或 IP，端口单独填写。': 'Enter a hostname or IP. Use the separate port field.', '端口需为 1–65535 之间的整数。': 'Use a whole-number port from 1 to 65535.', '密钥只能包含可打印 ASCII 字符。': 'The secret must contain printable ASCII characters only.', '保存远程机器': 'Save remote machine', '删除机器': 'Delete machine', '删除「{0}」及已保存的连接信息？{1}不会停止远程内核。': 'Delete “{0}” and its saved connection details? {1}The remote core will keep running.', '当前目标将切换回本机。': 'The target will switch to local. ', '删除远程机器': 'Delete remote machine',
  '清除': 'Clear', '清除{0}': 'Clear {0}', '端口需为 1024–65535 之间的整数。': 'Use whole-number ports from 1024 to 65535.', '端口需为 0–65535 之间的整数，0 表示关闭。': 'Use whole-number ports from 0 to 65535; 0 disables a port.', '已启用的代理端口不能重复。': 'Enabled proxy ports must be unique.', '请输入使用默认 443 端口的 HTTPS 链接，且不包含用户名、密码或片段标识。': 'Use an HTTPS URL on default port 443, without username, password or fragment.', '请输入有效的 HTTPS 订阅链接。': 'Enter a valid HTTPS subscription URL.', '[链接已隐藏]': '[URL hidden]',
  '界面语言': 'Language', '中文': '简体中文',
  '局域网': 'LAN', '未检测到局域网 IPv4 地址': 'No LAN IPv4 address detected', '复制局域网代理命令': 'Copy LAN proxy command', 'mips 需要 mihomo 1.19.31 或更新版本': 'mips requires mihomo 1.19.31 or later',
  '先启用 SSID 自动切换': 'Enable SSID auto switching first',
  '打开定位设置': 'Open location settings',
  '在文件夹中显示当前配置': 'Show current profile in folder', '复制消息': 'Copy message', '复制完整记录': 'Copy full record',
  '选择配置文件': 'Choose profile file', '覆盖配置「{0}」？': 'Overwrite profile “{0}”?', '覆盖配置': 'Overwrite profile',
  '同名配置将被替换。若该配置正在使用，内核将应用新内容；其他配置保留。': 'The profile with this name will be replaced. If it is active, the core will apply the new content. Other profiles remain available.',
  '检查订阅': 'Check subscription', '配置「{0}」已存在。确认后替换同名配置；正在使用时内核将应用新内容。': 'Profile “{0}” already exists. Confirm to replace it. An active core will apply the new content.',
};

export function t(message: string, ...values: unknown[]): string {
  const template = locale === 'en' ? english[message] ?? message : message;
  return template.replace(/\{(\d+)\}/g, (_, index: string) => String(values[Number(index)] ?? ''));
}

// 兼容旧版以可见文案保存的偏好，语言切换不会重置原有选项。
export function localizedPreference(value: string): string {
  const original = Object.entries(english).find(([, translated]) => translated === value)?.[0] ?? value;
  return t(original);
}
